# Generated by Django 5.2.13 on 2026-05-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('role', models.CharField(choices=[('worker', 'Сотрудник'), ('headworker', 'Руководитель'), ('admin', 'Администратор')], default='worker', max_length=20)),
                ('patronymic_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
