# Generated by Django 5.2.13 on 2026-05-05 10:58

from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    for user in User.objects.all():
        role = 'admin' if user.is_superuser else 'worker'
        profile, created = Profile.objects.get_or_create(user=user)
        if created:
            profile.role = role
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles),
    ]
